version: '3'

services:
  grozmerapi:
    image: grozmerapi:latest
    network_mode: bridge
    container_name: grozmer
    volumes:
      - /opt/upload-dir:/opt/upload-dir
    expose:
      - 8081
    ports:
      - 8081:8081
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/grozmer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=grozmer
    volumes:
      - /opt/postgresql/data:/var/lib/postgresql/data
  flyway:
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://postgres:5432/grozmer -schemas=public -user=postgres -password=password migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
    links:
      - postgres
