version: '3'

services:
  postgresql:
    image: postgres
    container_name: postgres
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=grozmer
    volumes:
      - /opt/postgresql/data:/var/lib/postgresql/data
  flyway:
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://postgres:5432/grozmer -schemas=public -user=postgres -password=password migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
